### ISSUE TITLE
Address issues from ruby-vs-js-objects as appropriate

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/ruby-object#1]
https://github.com/ga-wdi-boston/ruby-vs-js-objects/issues

**Comment by raq929** [comment]
ga-wdi-boston/ruby-vs-js-objects#21
ga-wdi-boston/ruby-vs-js-objects#16
ga-wdi-boston/ruby-vs-js-objects#15
ga-wdi-boston/ruby-vs-js-objects#17

**Comment by jrhorn424** [comment]
@raq929 Want me to open copies of those issues here so we can track when they're closed?

**Comment by raq929** [comment]
Sure.

**Comment by raq929** [comment]
I'm going to close this as I believe all these issues have been either referenced or addressed in this repo.
