### ISSUE TITLE
`bin/rake test` commands for testing labs should be rspec

### ISSUE THREAD

**Issue by BenGitsCode** [ga-wdi-boston/ruby-object#16]
test individual tests per lab, instead of all tests every time with rake. 

`rspec <spec_filename>`

**Comment by jrhorn424** [comment]
This conflicts with #6. I made a similar point there. This is a dupe in that case? Not sure. It's definitely something to talk about.

**Comment by BenGitsCode** [comment]
@raq929 ? Did I misunderstand the issue? What do you think about #6

**Comment by jrhorn424** [comment]
@gaand Originally opened #6. Follow the link in my OP there.

**Comment by BenGitsCode** [comment]
I just wanted to make sure I understood Rachel's intent when I opened this.

**Comment by BenGitsCode** [comment]
I think I have it completely backwards. That this issue should be changing the remaining rspec to rake instead, making this a duplicate to #6. Close this and have #6 addressed in 017 updates?

**Comment by raq929** [comment]
Yes plz.
